version: 1
disable_existing_loggers: false
formatters:
    simple:
        format: '%(asctime)s %(threadName)s %(levelname)s: %(message)s [%(module)s.py.%(lineno)s]'
    detail:
        format: "%(asctime)s %(threadName)s %(levelname)s  %(filename)s.%(funcName)s(): %(message)s"
    timing:
        format: '%(asctime)s %(threadName)s %(levelname)s, %(filename)s.%(funcName)s() (line %(lineno)s): %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    console_timing:
        class: logging.StreamHandler
        level: ERROR
        formatter: timing
        stream: ext://sys.stdout
    info_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: lazylibrarian-info.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8
    debug_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detail
        filename: lazylibrarian-debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf
    debug_timing_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: timing
        filename: lazylibrarian-debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf
loggers:
    unittest:
        level: INFO
        handlers: [console]
    special:
        level: DEBUG
        handlers: [console, debug_file]
        propagate: false
    special.cache:
        level: INFO
    special.configread:
        level: ERROR
    special.configwrite:
        level: ERROR
    special.dbcomms:
        level: INFO
    special.dbcomms.dbtiming:
        level: INFO
        propagate: false
        handlers: [console_timing, debug_timing_file]
    special.dlcomms:
        level: INFO
    special.fileperms:
        level: INFO
    special.fuzz:
        level: INFO
    special.iterateproviders:
        level: INFO
    special.libsync:
        level: INFO
    special.matching:
        level: INFO
    special.postprocess:
        level: INFO
    special.searching:
        level: INFO
root:
    level: INFO
    handlers: [console, info_file, debug_file]